# Generated by Django 2.2.5 on 2019-10-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('bun', models.CharField(max_length=300)),
                ('dan', models.CharField(max_length=300)),
                ('image', models.FileField(max_length=2000, upload_to='')),
                ('company', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_pw', models.CharField(max_length=50)),
                ('board_title', models.CharField(max_length=200)),
                ('board_content', models.TextField(max_length=2000)),
                ('board_user', models.CharField(max_length=50)),
                ('board_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
