# Generated by Django 2.2.5 on 2019-10-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardEx', '0002_auto_20191016_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
