# Generated by Django 2.2.5 on 2019-10-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardEx', '0003_delete_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odate', models.DateTimeField(auto_now_add=True)),
                ('omid', models.CharField(max_length=300)),
                ('oaid', models.CharField(max_length=300)),
                ('oquantity', models.CharField(max_length=300)),
            ],
        ),
    ]
