# Generated by Django 2.2.5 on 2019-10-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardEx', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='odate',
        ),
    ]
