# Generated by Django 2.2.5 on 2019-10-22 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardEx', '0005_remove_order_odate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
