# Generated by Django 2.2.5 on 2019-10-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('mid', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('mpassword', models.CharField(max_length=300)),
                ('mname', models.CharField(max_length=300)),
                ('mphone', models.CharField(max_length=300)),
                ('mpost_no', models.CharField(max_length=300)),
                ('maddress', models.CharField(max_length=300)),
                ('maddress_detail', models.CharField(max_length=300)),
            ],
        ),
    ]
